name: Draft Release with Executables

on:
  push:
    branches: ['main']
    tags: ['v*']

permissions:
  contents: write

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    # on tag OR '[cache]' in commit message on push
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      contains(github.event.head_commit.message, '[cache]')

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            triplet: x64-linux
            artifact_name: ssoc-linux
            # igraph uses some obscure libs not standard on ubuntu
            install: |
              sudo apt-get update
              sudo apt-get install -y \
                gcc-14 g++-14 gfortran-14 cmake ninja-build pkg-config libgl1-mesa-dev xorg-dev libasound2-dev libpulse-dev autoconf autoconf-archive automake libtool libltdl-dev

          - os: windows-latest
            triplet: x64-windows-static # static so its single executable
            artifact_name: ssoc-windows.exe
            install: echo "Nothing to do..."

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # due to igraph (versioning)

    - name: Install Dependencies
      shell: bash
      run: ${{ matrix.install }}

    - name: Create Cache Directory
      shell: bash
      run: |
        mkdir -p "${{ env.VCPKG_DEFAULT_BINARY_CACHE }}"

    - name: Restore vcpkg Cache
      id: vcpkg-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{ matrix.os }}-

    - name: Ensure vcpkg history
      # vcpkg comes pre-installed at $VCPKG_INSTALLATION_ROOT
      # by default the baseline commit in vcpkg.json might not be available
      shell: bash
      run: |
        if [ -d "$VCPKG_INSTALLATION_ROOT/.git" ]; then
            git -C "$VCPKG_INSTALLATION_ROOT" fetch --all --tags
        fi

    - name: Configure and Build
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          export CC=gcc-14 CXX=g++-14 FC=gfortran-14

        # ninja is better, uses vcpkg as config, static means its single exec
          cmake -B build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libstdc++ -static-libgcc"
        else
        # use msvc, multithreaded for single executable
          cmake -B build -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -DVCPKG_HOST_TRIPLET=${{ matrix.triplet }} \
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
        fi

        cmake --build build --config Release

    - name: Store vcpkg Cache
      # if cache already exists, don't save it again
      if: always() && steps.vcpkg-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir -p dist
        # windows might put is somwhere (not in bin),
        # also it have .exe which is not on unix
        find . -type f -name "ssoc*" -not -path "./dist/*" -exec cp {} dist/${{ matrix.artifact_name }} \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: dist/*
        if-no-files-found: error

  release:
    name: Create Draft Release
    needs: build
    runs-on: ubuntu-latest

    # only publish release on tags
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        path: release_dist
        merge-multiple: true

    - name: Publish Draft Release
      uses: softprops/action-gh-release@v2
      with:
        files: release_dist/*
        draft: true
        generate_release_notes: false
